# Replace "path" with your path to the data images for training and validation

train: "path/data/images/train"
val: "path/data/images/val"


nc: 1
names: ['brown_bear']

loss:
  box: 0.1
  cls: 0.4
  dfl: 1.0
